---
abstract: 'Catches common typos in POD'
author:
  - 'Apocalypse <APOCAL@cpan.org>'
configure_requires:
  Module::Build: 0.36
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Spell-CommonMistakes
provides:
  Pod::Spell::CommonMistakes:
    file: lib/Pod/Spell/CommonMistakes.pm
    version: 0.01
  Pod::Spell::CommonMistakes::WordList:
    file: lib/Pod/Spell/CommonMistakes/WordList.pm
    version: 0.01
requires:
  IO::Scalar: 2.110
  Pod::Spell: 1.01
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Pod-Spell-CommonMistakes
  homepage: http://search.cpan.org/dist/Pod-Spell-CommonMistakes
  license: http://dev.perl.org/licenses/
  repository: http://github.com/apocalypse/perl-pod-spell-commonmistakes
version: 0.01
